# fly.toml app configuration file generated for real-tracker on 2025-02-10T11:03:36+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'real-tracker'
primary_region = 'sin'

[build]

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1

[[services]]
  auto_stop_machines = "off"